# Generated by Django 3.1.2 on 2021-03-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20210310_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomodel',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='phone_number',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
