# Generated by Django 3.1.2 on 2021-03-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210310_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomodel',
            name='phone_number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
