# Generated by Django 3.1.2 on 2021-03-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20210310_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomodel',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
